#ifndef ROUTING_PLUGIN_COMMON_H
#define ROUTING_PLUGIN_COMMON_H

#define PLUGIN_NAME "routing plugin"

#define ROUTING_RIBS_COUNT 256
#define ROUTING_PROTOS_COUNT 256

#define BASE_YANG_MODEL "ietf-routing"

// base of all - routing container
#define ROUTING_CONTAINER_YANG_PATH "/" BASE_YANG_MODEL ":routing"

// router ID
#define ROUTING_ROUTER_ID_YANG_PATH ROUTING_CONTAINER_YANG_PATH "/router-id"

// interfaces container
#define ROUTING_INTERFACES_CONTAINER_YANG_PATH ROUTING_CONTAINER_YANG_PATH "/interfaces"
#define ROUTING_INTERFACE_LEAF_LIST_YANG_PATH ROUTING_INTERFACES_CONTAINER_YANG_PATH "/interface"

// control plane protocols container
#define ROUTING_CONTROL_PLANE_PROTOCOLS_CONTAINER_YANG_PATH ROUTING_CONTAINER_YANG_PATH "/control-plane-protocols"
#define ROUTING_CONTROL_PLANE_PROTOCOL_LIST_YANG_PATH ROUTING_CONTROL_PLANE_PROTOCOLS_CONTAINER_YANG_PATH "/control-plane-protocol"

// ribs
#define ROUTING_RIBS_CONTAINER_YANG_PATH ROUTING_CONTAINER_YANG_PATH "/ribs"
#define ROUTING_RIB_LIST_YANG_PATH ROUTING_RIBS_CONTAINER_YANG_PATH "/rib"
#define ROUTING_RIB_LIST_ACTIVE_ROUTE_RPC_PATH ROUTING_RIB_LIST_YANG_PATH "/active-route"

#endif // ROUTING_PLUGIN_COMMON_H